### ISSUE TITLE
autoflasher not working with firmware from 2015

### ISSUE THREAD

**Issue by eriu** [digineo/gluon-autoflasher#1]
moin moin,

ich habe soeben den autoflasher ausprobiert mit:

* WR841N v8 00000000
	* 3.15.9 Build 140724 Rel.63227n (24.07.2014) - hier funktioniert er ohne Probleme

		bash autoflash.sh
		mac address: c0:4a:00:84:5b:f8
		found model: WR841N
		hw version:  WR841N v8
		flashing image: images/gluon-ffmd-0.33-tp-link-tl-wr841n-nd-v8.bin ... done :)
		waiting for router to come up again ........................................ \o/

* jedoch unter der 9er Version mit aktuellerer Hard- und Software erkennt das skript die HW Version nicht mehr. Die Loginseite besteht mit der Firmware 141013 aus einerm GUI mit User/pwd Feld.
* WR841N v9 00000000
	* 3.16.9 Build 141013 Rel.61626n  (13.10.2014)

		bash autoflash.sh
		mac address: 30:b5:c2:81:08:32
		found model: WR841N
		WR841N
		WR841N
		hw version:  WR841N
		WR841N
		WR841N
		UNKNOWN MODEL (WR841N
		WR841N
		WR841N), SORRY :(

weitere Testes mit folgenden Geräten waren auch nicht erfolgreich:

* WR1043ND v1 00000000
	* 3.13.15 Build 140319 Rel.41339n (from 19/03/14)
	* http://www.tp-link.de/download/TL-WR1043ND_V1.html#Firmware
	
* WR1043ND v2 00000000
	* 3.19.32 Build 150717 Rel.53114n (from 11/08/15)
	* http://www.tp-link.de/download/TL-WR1043ND_V2.html#Firmware
			
			mac address: 
			found model: WR1043N
			WR1043N
			hw version:  WR1043N
			WR1043N
			UNKNOWN MODEL (WR1043N
			WR1043N), SORRY :(

* WDR3600 v1 00000000
	* 3.14.3 Build 150518 Rel.72050n (from 18/05/15)
        * http://www.tp-link.de/download/TL-WDR3600.html#Firmware
	
			mac address: 
			found model: WDR3600
			WDR3600
			hw version:  WDR3600
			WDR3600
			UNKNOWN MODEL (WDR3600
			WDR3600), SORRY :(
			
* WDR4300 v1 00000000
	* 3.14.3 Build 150518 Rel.70901n (fro 18/05/15)
	* http://www.tp-link.de/download/TL-WDR4300.html#Firmware

			mac address: 
			found model: WDR4300
			WDR4300
			hw version:  WDR4300
			WDR4300
			UNKNOWN MODEL (WDR4300
			WDR4300), SORRY :(

es schein also ein Problem seit dem Update der Stockfirmware zu geben

[wdr3600-v1.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75574/wdr3600-v1.MenuRpm.txt)
[wdr4300-v1.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75575/wdr4300-v1.MenuRpm.txt)
[wr1043nd-v1.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75576/wr1043nd-v1.MenuRpm.txt)
[wr1043nd-v2.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75577/wr1043nd-v2.MenuRpm.txt)

**Comment by corny** [comment]
Ich brauche die `/userRpm/StatusRpm.htm`:
```
curl --basic -u admin:admin -e http://192.168.0.1/userRpm/MenuRpm.htm http://192.168.0.1/userRpm/StatusRpm.htm
```

**Comment by eriu** [comment]
der 1043v1 hat in der oben genannten Version die standard IP Adresse http://192.168.1.1/

anbei die StatusRpm.htm der vier Geräte
[wr1043nd-v1.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75624/wr1043nd-v1.MenuRpm.txt)
[wr1043nd-v2.MenuRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75625/wr1043nd-v2.MenuRpm.txt)
[wrd3600-v1-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75626/wrd3600-v1-StatusRpm.txt)
[wrd4300-v1-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75627/wrd4300-v1-StatusRpm.txt)

**Comment by eriu** [comment]
neuer Versuch
[wr1043-v1-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75640/wr1043-v1-StatusRpm.txt)
[wr1043-v2-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75641/wr1043-v2-StatusRpm.txt)
[wrd3600-v1-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75642/wrd3600-v1-StatusRpm.txt)
[wrd4300-v1-StatusRpm.txt](https://github.com/digineo/gluon-autoflasher/files/75643/wrd4300-v1-StatusRpm.txt)

**Comment by eriu** [comment]
* WDR3600 v1 00000000 with 3.14.3 Build 150518 Rel.72050n (from 18/05/15)
      
		./autoflash 
		Waiting for 192.168.0.1 ... ✓
		Fetching model ... tp-link-tl-wdr3600-v1
		Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wdr3600-v1.bin .................................. ✓
		Uploading image ...  ✓
		Flashing ...  ✓
		Waiting for 192.168.1.1 ............................................... ✓`

* WDR4300 v1 00000000 with 3.14.3 Build 150518 Rel.70901n (from 18/05/15)
		
		./autoflash 
		Waiting for 192.168.0.1 ... ✓
		Fetching model ... tp-link-tl-wdr4300-v1
		Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wdr4300-v1.bin .................................. ✓
		Uploading image ...  ✓
		Flashing ...  ✓
		Waiting for 192.168.1.1 ................................................ ✓

**Comment by eriu** [comment]
* WR1043ND v2 00000000 with 3.19.32 Build 150717 Rel.53114n (from 11/08/15)

		./autoflash 
		Waiting for 192.168.0.1 ... ✓
		Fetching model ... Traceback (most recent call last):
		
  		File "./autoflash", line 8, in <module>
    autoflasher.Run()
    		File "lib/autoflasher.py", line 158, in Run
    AutoFlasher("192.168.0.1")
   		 File "lib/autoflasher.py", line 100, in __init__
    self.model = ExtractModel(self.request("status", "menu").text)
    		File "lib/autoflasher.py", line 43, in ExtractModel
    raise UnknownModel("Unable to extract model information")
	autoflasher.UnknownModel: Unable to extract model information

**Comment by eriu** [comment]
für 1043v2 [unknown-model.html.txt](https://github.com/digineo/gluon-autoflasher/files/75945/unknown-model.html.txt)

**Comment by eriu** [comment]
* WR1043ND v1 00000000 with 3.13.15 Build 140319 Rel.41339n (from 19/03/14)

		./autoflash 
		Waiting for 192.168.1.1 ... ✓
		Fetching model ... tp-link-tl-wr1043n-nd-v1
		Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wr1043n-nd-v1.bin .................................. ✓
		Uploading image ...  ✓
		Flashing ...  ✓
		Waiting for 192.168.1.1 ... ✓

**Comment by eriu** [comment]
* works with 841n v9 with https://github.com/digineo/gluon-autoflasher/commit/60b465ebff4f7bcd1482b0a0be44da2c446b4528

* WR841N v9 00000000 with 3.16.9 Build 150310 Rel.54318n (from 10/03/15)
* cookie: Basic%20YWRtaW46MjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzM%3D	
* http://www.tp-link.com/en/download/TL-WR841ND_V9.html#Firmware

    	./autoflash 
    	Waiting for 192.168.0.1 ... ✓
    	Fetching model ... tp-link-tl-wr841n-nd-v9
    	Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wr841n-nd-v9.bin .................. ✓
    	Uploading image ...  ✓
    	Flashing ...  ✓
    	Waiting for 192.168.1.1 ........................................................................... ✓

**Comment by eriu** [comment]
* works with 841n v11 with https://github.com/digineo/gluon-autoflasher/
* commit/60b465ebff4f7bcd1482b0a0be44da2c446b4528

* WR841N v11 00000000 (150616 from 16/06/15)
* http://www.tp-link.com/en/download/TL-WR841N_V11.html#Firmware

    	./autoflash 
		Waiting for 192.168.0.1 ... ✓
		Fetching model ... tp-link-tl-wr841n-nd-v10
		Downloading http://firmware.md.freifunk.net/experimental/factory/gluon-ffmd-0.33+5-g7621dd6-tp-link-tl-wr841n-nd-v10.bin .................. ✓
		Uploading image ...  ✓
		Flashing ...  ✓
		Waiting for 192.168.1.1 ............................................................................ ✓
[841n-v10.html.txt](https://github.com/digineo/gluon-autoflasher/files/75986/841n-v10.html.txt)

**Comment by eriu** [comment]
works with 841n v8 with https://github.com/digineo/gluon-autoflasher/
* WR841N v8 00000000 with 3.15.9 Build 140724 Rel.63227n (from 24/07/14)
* cookie: -
* http://www.tp-link.de/download/TL-WR841N_V8.html#Firmware

		./autoflash 
		Waiting for 192.168.0.1 ... ✓
		Fetching model ... tp-link-tl-wr841n-nd-v8
		Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wr841n-nd-v8.bin .................. ✓
		Uploading image ...  ✓
		Flashing ...  ✓
		Waiting for 192.168.1.1 .................................................................................... ✓

[841n-v8.html.txt](https://github.com/digineo/gluon-autoflasher/files/75989/841n-v8.html.txt)

**Comment by corny** [comment]
Erledigt durch 3bed6dfbc4c83f3383a409e82752a694784f7277, 60b465ebff4f7bcd1482b0a0be44da2c446b4528 und a277f71aaf5d6e77825bf9e873d8874180b78c7b.
