### ISSUE TITLE
add support for 841n v10 an other devices

### ISSUE THREAD

**Issue by eriu** [digineo/gluon-autoflasher#2]
after gluon release 2015.2 it will be great if the autoupdater will work with more types of devices

linke 841n v10 or  other gluon devices (https://github.com/freifunkMUC/autoflasher/blob/master/autoflash.sh)

-> https://github.com/digineo/gluon-autoflasher/blob/master/lib/autoflasher.py#L41

**Comment by corny** [comment]
Support has been added.
